name: Deploy to WordPress.org
on:
  push:
    branches:
      - implement-ci-cd

jobs:
  tag:
    name: Deploy Wordpress Plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_USERNAME: ${{ secrets.WORDPRESS_PLUGIN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WORDPRESS_PLUGIN_PASSWORD }}
        SLUG: softinn-booking-engine
        VERSION: 2.1.2