name: Deploy to WordPress.org
on:
  push:
    branches:
      - implement-ci-cd

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_USERNAME: ${{ secrets.WORDPRESS_PLUGIN_PASSWORD }}
        SVN_PASSWORD: ${{ secrets.WORDPRESS_PLUGIN_PASSWORD }}
        SLUG: softinn-booking-engine